# Xelians Export

Exploratory Data Analysis

### Xelians files

In [22]:
import pandas as pd

df_files = pd.read_csv("xelians-filenames.csv", sep="_")
df_files.head()

,idContract,idCourier,codeTypology,xeliansFilename
0,039571-a2d99e05-3023-ea11-a2d5-0050569c0763,357c1839-1449-4f40-976e-b886e4c4ba26,C049,pdf
1,039571-a2d99e05-3023-ea11-a2d5-0050569c0763,357c1839-1449-4f40-976e-b886e4c4ba26,C051,pdf
2,039571-a2d99e05-3023-ea11-a2d5-0050569c0763,357c1839-1449-4f40-976e-b886e4c4ba26,C076,pdf
3,039571-a2d99e05-3023-ea11-a2d5-0050569c0763,357c1839-1449-4f40-976e-b886e4c4ba26,C105,pdf
4,039571-a2d99e05-3023-ea11-a2d5-0050569c0763,357c1839-1449-4f40-976e-b886e4c4ba26,C107,pdf

In [23]:
df_files.info()

<class 'pandas.DataFrame'>
RangeIndex: 1043 entries, 0 to 1042
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   idContract       1043 non-null   str
 1   idCourier        1043 non-null   str
 2   codeTypology     1043 non-null   str
 3   xeliansFilename  1043 non-null   str
dtypes: str(4)
memory usage: 32.7 KB

In [24]:
df_files.drop_duplicates().count()

idContract         1043
idCourier          1043
codeTypology       1043
xeliansFilename    1043
dtype: int64

In [25]:
df_files.describe()

,idContract,idCourier,codeTypology,xeliansFilename
count,1043,1043,1043,1043
unique,113,135,61,3
top,121772-c88a5746-d988-f011-b4cc-6045bda1ae8e,b01ae5ae-ac3d-4bb1-b818-e4c41c00e9b5,C069,pdf
freq,40,19,102,997

In [26]:
df_files.groupby("idContract").count()

,idCourier,codeTypology,xeliansFilename
idContract,,,
039571-a2d99e05-3023-ea11-a2d5-0050569c0763,5,5,5
105595-48fcaaca-4e0f-ef11-9f89-6045bd9909e7,11,11,11
110025-16f5ae47-2ca7-ef11-b8e8-7c1e525e9311,6,6,6
111279-128e2e94-66cf-ef11-b8e8-6045bd930ece,9,9,9
111469-65644199-bfd4-ef11-8eea-000d3aac506b,5,5,5
...,...,...,...
124878-011cc928-c0c3-f011-bbd3-6045bd8f8f87,7,7,7
125145-61fc4c87-26c6-f011-bbd3-7ced8d0f70f6,6,6,6
125856-7ae60381-852c-ef11-840a-000d3a499c98,7,7,7
127302-681bef83-73d7-f011-8544-6045bd8f8f87,6,6,6
127336-2697de58-b0e0-f011-8544-7ced8d101822,7,7,7

In [27]:
df_files.groupby("codeTypology").count()

              idContract  idCourier  xeliansFilename
codeTypology
20                    13         13               13
A003                   1          1                1
C003                  82         82               82
C004                 101        101              101
C005                   3          3                3
...                  ...        ...              ...
C901                   4          4                4
C906                   3          3                3
C907                   1          1                1
C908                   2          2                2
C910                   3          3                3

[61 rows x 3 columns]

### Xelians codes

In [28]:
df_codes = pd.read_csv("Xelians-DocumentType.csv", sep=",")
df_codes.head()

,XeliansCode,Description,FrenchLabel,EnglishLabel
0,A001,Dossier de souscription Arkéa (PP),Dossier de souscription Arkéa (PP),Arkea subscription form (Individual)
1,A002,Dossier de souscription Arkéa (2PP),Dossier de souscription Arkéa (2PP),Arkea subscription form (Two individual)
2,A003,Dossier de souscription Arkéa (PM),Dossier de souscription Arkéa (PM),Arkea subscription form (Legal entity)
3,C001,BS CC - Souscription,CORUM Origin - Bulletin de souscription,CORUM Origin - Subscription Form
4,C002,TITRE DE PROPRIETE,Titre de propriété,Title of ownership

In [29]:
df_codes.describe()

,XeliansCode,Description,FrenchLabel,EnglishLabel
count,234,234,234,234
unique,234,215,170,170
top,A001,CORUM XL - Bulletin de souscription,Document lié au financement par Corum,Document related to financing by Corum
freq,1,4,19,19

### Merged dataframes

In [30]:
code_to_label = df_codes.set_index("XeliansCode")["FrenchLabel"]
df_files["codeTypology"] = df_files["codeTypology"].map(code_to_label)

In [33]:
df_files['codeTypology'].describe()

count                           1043
unique                            50
top       Documents d'audit/contrôle
freq                             102
Name: codeTypology, dtype: object